'''
Problem 29
Considering all integer combinations of a**b for 2 <= a <= 5 and 2 <= b <= 5, there are 15 distinct evaluations.
How many distinct numbers are generated by a**b for  2 <= a <= 100 and 2 <= b <= 100.
'''
limit = 100
nums = set()
for a in range(2,limit+1):
    for b in range(2,limit+1):
        nums.add(a**b)

print(len(nums))
