'''
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''

def P(n):
    return n*(3*n-1)//2

def isP(p):
    n = (1 + (1 + 24*p)**0.5) / 6
    return n == int(n)

minD = float('inf')
for j in range(1,10000):
    for k in range(j,10000):
        Pj = P(j)
        Pk = P(k)
        diff = abs(Pj-Pk)
        if isP(diff) and isP(Pj+Pk):
            print(j,k)
            if diff < minD:
                minD = diff
print(minD)