'''
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle   Tn = n(n + 1)/2   1,3,6,10,15, ...
Pentagonal Pn = n(3n - 1)/2  1,5,12,22,35, ...
Hexagonal  Hn = n(2n-1)      1,6,15,28,45, ...

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
'''

def T(n):
    return n*(n + 1)//2

def isP(p):
    n = (1 + (1 + 24*p)**0.5) / 6
    return n == int(n)

def isH(h):
    n =(1 + (1 + 8*h)**0.5) / 4
    return n == int(n)

n = 285
while True:
    n += 1
    t = T(n)
    if isP(t) and isH(t):
        print(t)
        break
